services:
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434:11434'
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=riotapi'
      - 'POSTGRES_PASSWORD=supremelysecret'
      - 'POSTGRES_USER=root'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'